name: ms-mint-app-test_dep
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - -e ../ms-mint
      - -e .
      - mkdocs
      - mkdocs-material
      - flake8
      - pytest
