[build-system]
requires = ["setuptools>=70", "wheel", "versioneer[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "ms-mint-app"
description = "Metabolomics Integrator Interactive Web-Application (Mint)"
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}
authors = [
  {name = "Soren Wacker", email = "swacker@ucalgary.ca"}
]
maintainers = [
  {name = "Soren Wacker", email = "swacker@ucalgary.ca"}
]
keywords = ["metabolomics", "integrator", "mint"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent"
]
dependencies = [
  "ms-mint",
  #  "ms-mint @ git+https://github.com/Valdes-Tresanco-MS/ms-mint.git",
  "xlsxwriter",
  "pandas==2.3.2",
  "numpy==2.3.3",
  "plotly==6.3.1",
  "psutil==7.1.0",
  "polars==1.33.1",
  "waitress",
  "dash",
  "dash[diskcache]",
  "dash_extensions",
  "dash_bootstrap_components",
  "flask_login",
  "flask_migrate",
  "flask_wtf",
  "urllib3",
  "dash_tabulator",
  "dash_uploader==0.7.0a1",
  "beautifulsoup4",
  "h5py",
  "hdf5plugin",
  "werkzeug==3.0.6",
  "packaging==21.3.0",
  "email-validator",
  "feffery-antd-components==0.4.2",
  "feffery-utils-components==0.3.3",
  "plotly-resampler==0.11.0",
  "duckdb==1.4.1",
  "distinctipy==1.3.4",
  "tqdm>=4.67.1",
  "scikit-learn>=1.6.1",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/LewisResearchGroup/ms-mint-app"
Documentation = "https://lewisresearchgroup.github.io/ms-mint-app/"
Repository = "https://github.com/LewisResearchGroup/ms-mint-app.git"
"Bug Tracker" = "https://github.com/LewisResearchGroup/ms-mint-app/issues"

[project.scripts]
Mint = "ms_mint_app.scripts.Mint:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["ms_mint_app*"]

[tool.setuptools.package-data]
"ms_mint_app.assets" = ["*.css"]

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "src/ms_mint_app/_version.py"
tag_prefix = "v"
parentdir_prefix = ""

[tool.setuptools.dynamic]
version = { attr = "ms_mint_app.__version__" }
