name: Docker Image CI

on:
  push:
    branches:
      - dockerhub
  release:
    types: [published]
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag your-docker-repo/your-image:latest --no-cache
    - name: Push Docker Image
      run: docker push your-docker-repo/your-image:latest
