name: Docker Image CI

on:
  push:
    branches:
      - dockerhub  # Trigger workflow on pushes to the dockerhub branch
  release:
    types: [published]  # Trigger workflow on new releases
  workflow_dispatch:    # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build Docker Image
      run: docker build . --file Dockerfile --tag your-docker-repo/your-image:latest --no-cache

    - name: Push Docker Image
      run: docker push your-docker-repo/your-image:latest
